sonar.projectKey=nutrired
sonar.projectName=NutriRed
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.scanner.skipJreProvisioning=true
